# Generated by Django 3.2.16 on 2023-08-22 19:01

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Сначала пусто', max_length=256, null=True, verbose_name='Название')),
                ('description', models.TextField(default='Сначала пусто', verbose_name='Текст')),
                ('slug', models.SlugField(default='Сначала пусто', unique=True, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Сначала пусто', max_length=256, verbose_name='Имя локации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Когда, во-сколько создано:')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Сначала пусто', max_length=256, null=True, verbose_name='Название')),
                ('text', models.TextField(default='Сначала пусто', verbose_name='Текст')),
                ('pub_date', models.DateTimeField(verbose_name='Когда, во-сколько опубликовано:')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Когда, во-сколько создано:')),
                ('author', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='Категория')),
                ('location', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ('title',),
            },
        ),
    ]
